service: ezcloud
provider:
  name: aws
  runtime: python3.7
  region: us-east-1

custom:
  pythonRequirements:
    dockerizePip: true

package:
  individually: false
  exclude:
    - package.json
    - package-log.json
    - node_modules/**

functions:
  ezcloud:
    handler: handler.ezcloud
    events:
      - http:
          path: ezcloud
          method: get

plugins:
  - serverless-python-requirements
