name: deploy-aws-lambda

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

    #credentials to connect to AWS
    - name: Configure AWS credentials from Production account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        args: deploy
      env:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1
        profile_name: default
        project_name: serverless
        runtime: python3.7
      - name: Install Dependencies
        run: npm ci
        with:
          args: deploy 
      - name: Serverless Deploy
        run: npm run-script deploy
            #Deploy main.py to AWS
      - name: AWS Lambda Deploy
        uses: appleboy/lambda-action@v0.0.4
        with:
    #name of my AWS Lambda Function
      function_name: gittolambda
    #contains all the files in my github repository
      zip_file: gittolambda.zip